### ISSUE TITLE
Comments requested for Metal / GTK4 integration example 

### ISSUE THREAD

**Issue by habemus-papadum** [JuliaGtk/Gtk4.jl#22]
Hi,
Both as an fyi, and as a request for comments, here is an example of using Metal and GTK4. 
https://github.com/JuliaGPU/Metal.jl/blob/main/examples/gtk.jl 

In particular, I am curious if there is a cleaner way to achieve
https://github.com/JuliaGPU/Metal.jl/blob/fdab27774c5f4b96ad7fc8bafee698394dde8e70/examples/gtk.jl#L45-L46

Or any other comments.  

Thanks for having a look and your hard work!  lmk if there is gtk4 slack or discourse or other location for this sort of thing. Cheers, nehal

**Comment by jwahlstrand** [comment]
It's a shame you have to create a GdkPixbuf just to display it, since it means getting the data from the GPU and then sending it right back to the GPU through GTK4 (as far as I understand), but that is probably the only way to do it currently.

For your particular question you might want to look into whether GtkImage or GtkPicture is the right widget to use:
https://docs.gtk.org/gtk4/migrating-3to4.html#adapt-to-gtkimage-changes

GtkPicture also has a `set_pixbuf` method.

From the GTK4 docs it's not clear to me which would be best for your case.

**Comment by habemus-papadum** [comment]
Actually macs w/ apple silicon (currently only supported by Metal.jl) can used unified memory between the GPU and CPU,so in this example no memory is being copied.  Have a look at https://github.com/JuliaGPU/Metal.jl/blob/main/examples/unified_memory.jl for for info.  

Thanks, nehal

**Comment by jwahlstrand** [comment]
In the long term there may be a more efficient way of doing the drawing using GdkPaintable but I'm not sure how to support that in Gtk4.jl yet. I'll leave this open as a reminder to look into that.
