### ISSUE TITLE
Apply for GNOME Circle

### ISSUE THREAD

**Issue by gregorni** [JuliaGtk/Gtk4.jl#52]
Since recently, GTK bindings can apply for [GNOME Circle](https://circle.gnome.org/) membership. If the bindings are accepted, this would attract contributors to the project. The current review process for GTK languahe bindings is still a bit shaky, there's no harm in applying.

Seeing as the libadwaita bindings aren't yet registered or documented, it may be a good time to apply _after_ that has happened.

**Comment by jwahlstrand** [comment]
Thanks for reaching out, but I don't think it's time yet for a few reasons:

1. As far as I know, there is no way of producing Flatpak-installable apps using Julia, which seems to be a big emphasis of GNOME Circle. People _are_ working on ways of producing apps using Julia, e.g. https://github.com/PeaceFounder/AppBundler.jl, but I can't point to a single example using Gtk4.jl.
2. The libadwaita issue. Registering the bindings would be very easy, the reason I haven't is because they are not documented. I don't use libadwaita myself (GTK4 is sufficient for me) and I don't foresee having the time to write documentation in the near future. So if that is a barrier to acceptance, it's not going to change any time soon unless someone else steps up.
3. I see that PyGObject and Vala haven't been accepted yet. I view those as mature, widely deployed bindings. Until they have passed with flying colors, and I see how the process works, I don't see a reason to submit Gtk4.jl.

**Comment by gregorni** [comment]
> As far as I know, there is no way of producing Flatpak-installable apps using Julia.

This might change in the future, but you're probably right, that would be a blocking issue.

> The libadwaita issue

That is not strictly a problem, you can always submit only the bindings that are supported.

> I see that PyGObject and Vala haven't been accepted yet

I'm part of the Circle Committee myself, and the reason for this is we basically don't have guidelines/requirements for reviewing GTK bindings. There's no proper review mechanism for them in place yet, although that's something I've been working on lately.

In the end, it's up to you to decide if the bindings are mature enough to apply for Circle, but at least now you know the option is there.
